spring:
  profiles:
    active: dev
  application:
    name: MQTT_SERVER
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        file-extension: yaml
      server-addr: localhost:8848
  cache:
    type: caffeine
  redis:
    port: 6379
    host: 127.0.0.1
    password:
    jedis:
      pool:
        max-idle: 32
        max-active: 64
        max-wait: 2000ms
    database: 3
  data:
    mongodb:
      uri: mongodb://localhost/test
iot-server:
  port: 1883
  version: BQ-KS
logging:
  file:
    path:
    name: D:\data\log\iot-mqtt-server.log
  level:
    com: trace
server:
  port: 8850

ribbon:
  #http请求连接建立超时时间（ms）
  ConnectTimeout: 10000
  #http请求处理超时时间（ms）
  ReadTimeout: 15000
  #默认重试次数
  MaxAutoRetries: 1
  #默认尝试的实例数
  MaxAutoRetriesNextServer: 4
