spring:
  cache:
    type: redis
    cache-names: MQTT
    redis:
      key-prefix: MQTT
  redis:
    port: 6379
    url: 127.0.0.1:6379
    host: 127.0.0.1
    password:
    jedis:
      pool:
        max-idle: 32
        max-active: 64
        max-wait: 2000ms