spring:
  cache:
    type: caffeine
  redis:
    port: 6379
    host: 127.0.0.1
    password:
    jedis:
      pool:
        max-idle: 32
        max-active: 64
        max-wait: 2000ms
    database: 3
  data:
    mongodb:
      uri: mongodb://localhost/test
iot-server:
  port: 1883
  version: BQ-KS
logging:
  file:
    path:
    name: D:\data\log\iot-mqtt-server.log
  level:
    com.risky: trace
server:
  port: 8456
  address: 0.0.0.0